### ISSUE TITLE
py file not found

### ISSUE THREAD

**Issue by DeepakChoudhary101** [XiangLi2022/CM-TTS#1]
Traceback (most recent call last):
  File "/mnt/d/deepak's work/paper_3/CM-TTS/synthesize.py", line 15, in <module>
    from utils.model import get_model, get_vocoder
  File "/mnt/d/deepak's work/paper_3/CM-TTS/utils/model.py", line 13, in <module>
    from model.cm_tool.script_util import (
  File "/mnt/d/deepak's work/paper_3/CM-TTS/model/cm_tool/script_util.py", line 6, in <module>
    from .tts_net import CMDenoiserTTS, CMTotalTTS
  File "/mnt/d/deepak's work/paper_3/CM-TTS/model/cm_tool/tts_net.py", line 7, in <module>
    from ..diffgantts import DurationPitchSpeakerNet
ModuleNotFoundError: No module named 'model.diffgantts'

**Comment by sabahmax-inc** [comment]
Hi! Thanks for flagging this. I’ve opened [PR #4](https://github.com/XiangLi2022/CM-TTS/pull/4), which fixes the missing `model.diffgantts` import issue so `synthesize.py` should run without the `ModuleNotFoundError`.
